name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Instalar pytest
      - name: Install pytest
        run: pip install pytest

      # Paso 1: Ejecutar pruebas unitarias
      - name: Run unit tests
        run: pytest

      # Paso 2: Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t app_image:1.0 .

      # Paso 3: Ejecutar la imagen Docker
      - name: Run Docker container
        run: docker run -d -p 8000:8000 app_image:1.0 .

      # Paso 4: Ejecutar pruebas de integración
      - name: Run integration tests
        run: sh integration_testing/curl_testing.sh

      # Paso 5: Empujar la imagen Docker a un registro
      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 
          docker push fabiocajamarca/application_1:1.0
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
